create extension plpython3u;
DROP TABLE IF EXISTS zoo_1;
DROP TABLE IF EXISTS zoo_2;
CREATE TABLE zoo1 (id int, animal text);
INSERT into zoo1 (id, animal) VALUES (1, 'Lion'), (2, 'Tiger'), (3, 'Wolf'), (4, 'Fox');
CREATE TABLE zoo2 (id int, animal text);
INSERT into zoo2 (id, animal) VALUES (1, 'Tiger'), (2, 'Lion'), (3, 'Rhino'), (4, 'Panther');
DROP SCHEMA IF EXISTS test_Schema CASCADE;
DROP SCHEMA IF EXISTS "test_Schema" CASCADE;
CREATE Schema "test_Schema";
CREATE SCHEMA test_Schema;