#@ load("job_def.lib.yml",
#@   "entrance_job",
#@   "exit_pr_job",
#@   "build_test_job",
#@   "centos7_gpdb6_conf",
#@   "rhel8_gpdb6_conf",
#@   "ubuntu18_gpdb6_conf",
#@   "rocky8_gpdb7_conf",
#@ )
#@ load("trigger_def.lib.yml",
#@   "pr_trigger",
#@ )
#@ load("base.lib.yml",
#@   "declare_res",
#@  "declare_res_type")
#@ res_map = {}
#@ res_type_map = {}
#@ trigger = pr_trigger(res_map)
#@ confs = [
#@   centos7_gpdb6_conf(),
#@   rhel8_gpdb6_conf(),
#@   ubuntu18_gpdb6_conf(),
#@   rocky8_gpdb7_conf(),
#@ ]
jobs:
#@ param = {
#@     "res_map": res_map,
#@     "trigger": trigger,
#@ }
- #@ entrance_job(param)
#@ for conf in confs:
#@   param = {
#@     "res_map": res_map,
#@     "trigger": trigger,
#@     "conf": conf
#@   }
- #@ build_test_job(param)
#@ end
#@ param = {
#@     "trigger": trigger,
#@     "confs": confs
#@ }
- #@ exit_pr_job(param)

resources: #@ declare_res(res_type_map, res_map)

resource_types: #@ declare_res_type(res_type_map)
